#!/bin/sh
set -euo

declare -a pairs

case "${1}" in
    *+*)
        pair=(${1//+/ })
        pairs=("${pair[0]} ${pair[1]}" "${pair[1]} ${pair[0]}")
        shift 1
        ;;
    *)
        pairs=("${1} ${2}")
        shift 2
        ;;
esac

runit() {
    local from="${1}"
    local to="${2}"
    local interface="${3}"
    local container="dev-cluster-emqx${from}-1"
    shift 3
    docker exec --privileged "${container}" tc qdisc del dev "${interface}" parent 1:${to} || true
    docker exec --privileged "${container}" tc qdisc add dev "${interface}" parent 1:${to} "$@"
}

for pair in "${pairs[@]}"; do
    for interface in $(seq 0 1); do
        runit ${pair} "eth${interface}" "$@"
    done
done
