#!/bin/sh
set -ex

# Node where to apply the rule:
at="${1}"
# Target node:
to="${2}"
shift 2

container="dev-cluster-emqx${at}-1"

runit() {
    local interface=$1
    shift 1
    docker exec --privileged ${container} tc qdisc del dev "${interface}" parent 1:${to} || true
    docker exec --privileged ${container} tc qdisc add dev "${interface}" parent 1:${to} "$@"
}

for i in $(seq 0 1); do
    runit "eth${i}" "$@"
done
